#!/bin/bash

echo "Running git pre-push hook"

./gradlew detekt

RESULT=$?

# return 1 exit code if running checks fails
[ $RESULT -ne 0 ] && echo "ERROR: detekt check failed. Please fix the issues and re-commit." &&  exit 1
exit 0
