name: Check CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Putting data to api_token
        env:
          DATA: ${{ secrets.API_KEY }}
        run: echo $DATA > ./app/src/main/java/ru/kheynov/todoappyandex/core/data/util/ApiToken.kt
      - name: Build with Gradle
        run: ./gradlew build
      - name: Linter Check
        run: ./gradlew detekt

